# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - vubinhan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: 📦 Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: ⚛️ Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: ⚛️ Build frontend React App
        working-directory: ./frontend
        run: npm run build

      - name: 🔁 Move React build into backend/frontend/
        run: |
          rm -rf backend/frontend
          mkdir -p backend/frontend
          cp -r frontend/build/* backend/frontend/

      - name: 📦 Install backend production dependencies only
        working-directory: ./backend
        run: npm install --omit=dev

      - name: 📦 Zip full backend (with React build)
        run: |
          cd backend
          zip -r ../release.zip .

      - name: ⬆️ Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: ⬇️ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: 📂 Unzip artifact
        run: unzip release.zip

      - name: 💤 Wait before deployment (fix SCM container restart)
        run: sleep 30

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_58C05D9F5EB54393AACD64B5EE499070 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_27A36A65853D43E0ADD285B4385D4490 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_39E3F6A46B964E2FA198BF142954C9D5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vubinhan'
          slot-name: 'Production'
          package: .
          
